import Head from "next/head";
import Footer from "../footer/Footer";
import Nav from "../nav/Nav";

export default function Main_Layout({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <main>{children}</main>
            <Footer />
        </>
    );
}
